name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Hugo and lunr
        run: |
          curl -L https://github.com//gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Windows-64bit.zip -o hugo.zip
          7z x hugo.zip -ohugo
          $env:PATH="$PWD\hugo\;$env:PATH"
          echo "$env:PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Install lunr
        run: |
          npm init -y
          npm install lunr
          npm install glob
          echo "installed"
          node "themes\minimo\scripts\generate-search-index-lunr.js"
      - name: Build Site
        run: |
          hugo --gc --minify --cleanDestinationDir
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
