name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugo and lunr
        run: |
          choco install hugo -confirm
          npm install -g lunr glob
      - name: Build Site
        shell: cmd
        run: |
          node ./themes/minimo/scripts/generate-search-index-lunr.js
          hugo --gc --minify --cleanDestinationDir
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
